### ISSUE TITLE
Multitype query

### ISSUE THREAD

**Issue by tyriis** [score-framework/py.es#1]
According to [https://www.elastic.co/guide/en/elasticsearch/guide/master/multi-index-multi-type.html](https://www.elastic.co/guide/en/elasticsearch/guide/master/multi-index-multi-type.html) it is possible to search in different types, it would be nice to have this functionality in py.es.

it would be nice if it looks like this:

`ctx.es.query([db.User, db.Channel, ...], dsl, offset=offset, limit=limit)`

without breaking compatibility, so 

`ctx.es.query(db.User, dsl, offset=offset, limit=limit)`

is still possible.

**Comment by soulmerge** [comment]
Sounds reasonable. Implemented the requested feature in V0.2.4 as suggested: the first parameter to the function can now be a list of types.
